name: Deploy React App to CWP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies & Build
        run: |
          npm install --legacy-peer-deps
          npm run build:ci

      - name: Zip build files
        run: |
          tar -czvf build.tar.gz -C build .

      - name: Copy Zip to Server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22527
          source: "build.tar.gz"
          target: "/home/sustylo/"

      - name: Unzip files on Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22527
          script: |
            rm -rf /home/sustylo/public_html/*
            mkdir -p /home/sustylo/public_html
            tar -xzvf /home/sustylo/build.tar.gz -C /home/sustylo/public_html
            rm /home/sustylo/build.tar.gz
